name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Gera diariamente à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: SEU-USUARIO
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "generate snake animation"
          git push
