name: Snake animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  workflow_dispatch:     # Permite executar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: RafaMirandaCAP
          svg_out_path: .github/workflows/snake.svg

      - name: Commit da cobrinha gerada
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: github-actions[bot]@users.noreply.github.com
          message: Atualizando o Snake
          add: .github/workflows/snake.svg
